name = "Lithuanian"
version = "0.1.0"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Lithuanian spellchecker"
lt = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Lithuanian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
lt = "TRANSLATE: A spellchecker for Lithuanian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.lt"

[windows]
system_product_code = "{52655167-414E-4851-9063-2B06A4297C8B}_is1"
