template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "lith1251"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-lit"
__UND2C__ = "lt"
__UNDEFINED__ = "Lithuanian"
__UND__ = "lit"
